#!/bin/sh
set -e
D=$(date +"%Y%m%d%H%M%S")

size="$(fbset|sed -n -e's/^mode.*\"\([0-9]\+x[0-9]\+\)[-\"].*$/\1/p')"
mirscreencast -m /var/run/mir_socket -n 1 -f /tmp/${D}.rgba
convert -depth 8 -size $size /tmp/${D}.rgba /home/phablet/Pictures/${D}.png
chown phablet:phablet /home/phablet/Pictures/${D}.png
/bin/rm /tmp/${D}.rgba
