/*
 * This file was generated by qdbusxml2cpp version 0.8
 *
 * ATTENTION: The PropertiesChanged signal is added manually
 *
 * Command line was: qdbusxml2cpp -a inputprovideradaptor -c InputProviderAdaptor org.aethercast.xml org.aethercast.InputProvider
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef INPUTPROVIDERADAPTOR_H
#define INPUTPROVIDERADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.aethercast.InputProvider
 */
class InputProviderAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.aethercast.InputProvider")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.aethercast.InputProvider\">\n"
"    <method name=\"NewConnection\">\n"
"      <arg direction=\"in\" type=\"h\" name=\"fd\"/>\n"
"      <arg direction=\"in\" type=\"a{sv}\" name=\"options\"/>\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In1\"/>\n"
"    </method>\n"
"    <method name=\"RequestDisconnection\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"cursor\"/>\n"
"  </interface>\n"
        "")
public:
    InputProviderAdaptor(QObject *parent);
    virtual ~InputProviderAdaptor();

public: // PROPERTIES
    Q_PROPERTY(QString cursor READ cursor)
    QString cursor() const;

public Q_SLOTS: // METHODS
    void NewConnection(const QDBusUnixFileDescriptor &fd, const QVariantMap &options);
    void RequestDisconnection();
Q_SIGNALS: // SIGNALS
    void PropertiesChanged(const QString &interface, const QVariantMap &changed, const QStringList &invalid);
};

#endif
